FROM python:3.10-slim

WORKDIR /code

COPY requirements.txt /code/
RUN pip install -r requirements.txt

ADD femo/ /code/femo/
ADD setup.py /code/setup.py
ADD README.md /code/README.md

RUN pip install .

CMD [ "python3" ]

