data_pipeline:
  base: &base
    description: "Only large piezos from belt types 'A' and 'C'"
    sensor_freq: 1024
    sensation_freq: 1024
    sensor_map:
      accelerometer:
        - 'sensor_1'
        - 'sensor_2'
      piezoelectric_large:
        - 'sensor_3'
        - 'sensor_6'
      other:
        - 'sensor_4'
        - 'sensor_5'
    sensor_selection:
      - 'piezoelectric_large'
  load:
    <<: *base
  preprocess:
    <<: *base
  segment:
    <<: *base
    imu_acceleration_threshold: 0.2
    imu_rotation_threshold: 4
    maternal_dilation_forward: 2.0
    maternal_dilation_backward: 5.0
    imu_dilation: 4.0
    fm_dilation: 3.0
    fm_min_sn: 40
    fm_signal_cutoff: 0.0001
  fusion:
    <<: *base
    desired_scheme: ['type', 1]
  extract_det:
    <<: *base
  extract_feat:
    <<: *base
    freq_mode_threshold: 1
    freq_bands:
      - [1, 2]
      - [2, 5]
      - [5, 10]
      - [10, 20]
      - [20, 30]




