feature_sets: ['crafted', 'tsfel']
feature_ranking:
  feat_ratio: 3
  param_cfg:
    nca_ranking:
      n_components: 30
      max_iter: 1000
    xgb_ranking:
      learning_rate: 0.01
      n_estimators: 100
      max_depth: 3
    logReg_ranking:
      solver: 'liblinear'
    recursive_ranking:
      step: 1
      estimator: 'AdaBoost'
