# options: 'neural-net', 'logReg', 'svc', 'adaboost', 'random-forest'
classifier:
  type: 'neural-net'
  config:
    search_space:
      ...
    hyperparameters:
      ...

train_params:
  epochs: 10
  batch_size: 32
  validation_split: 0.2