name: pr-validation-ci-check

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  # Enforce PRs from dev branch only when targeting main
  enforce-pr-from-dev:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'main'  # Only enforce when the target branch is 'main'
    steps:
      - name: Check if PR is from dev branch
        run: |
          if [[ "${{ github.head_ref }}" != "dev" ]]; then
            echo "Pull requests to main branch must come from the dev branch."
            exit 1
          fi
        shell: bash

  # CI check (runs after the enforce-pr-from-dev check passes)
  ci-check:
    runs-on: ubuntu-latest
    needs: enforce-pr-from-dev  # This ensures CI runs only after enforce-pr-from-dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - run: pip install virtualenv
      - run: bash scripts/test.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
