name: Enforce-PR-from-dev

on:
  pull_request:
    branches:
      - main

jobs:
  check-source-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is from dev branch
        run: |
          if [[ "${{ github.head_ref }}" != "dev" ]]; then
            echo "Pull requests to main branch must come from the dev branch."
            exit 1
          fi
        shell: bash
