name: Tag and Release on Version Change

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

jobs:
  tag-and-release:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Extract version
        id: get_version
        run: |
          # Extract the __version__ variable from femo/__init__.py
          version=$(grep '^__version__' femo/__init__.py | cut -d '"' -f 2)
          echo "Version found: $version"
          echo "version=$version" >> $GITHUB_ENV

      - name: Check for existing tag
        id: check_tag
        run: |
          git fetch --tags
          if git tag -l | grep -Fxq "v${{ env.version }}"; then
            echo "Tag v${{ env.version }} already exists."
            echo "tag_exists=true" >> $GITHUB_ENV
          else
            echo "v${{ env.version }} does not exist"
            echo "tag_exists=false" >> $GITHUB_ENV
          fi

      - name: Create Git tag and push
        if: env.tag_exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag "v${{ env.version }}"
          git push origin "v${{ env.version }}"

      - name: Create GitHub Release
        if: env.tag_exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ env.version }}" --title "v${{ env.version }}" --generate-notes
